# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
gems:
  - jekyll-sitemap

# Site settings
title: "Steven Maguire"
description: >
   Builder of Teams, Software Architect and Product Designer living in Chicago, IL
email: stevenmaguire@gmail.com
logo: "http://stevenmaguire-com.s3.amazonaws.com/assets/logo.png"
cover: "http://stevenmaguire-com.s3.amazonaws.com/assets/1487799_10101504743938103_1110083647_o.jpg"

name: 'Steven Maguire'
author: 'Steven Maguire'
author_image: "http://stevenmaguire-com.s3.amazonaws.com/assets/steven.png"
favicon: "http://stevenmaguire-com.s3.amazonaws.com/assets/favicon.ico"

paginate: 5

url: "http://stevenmaguire.com"
baseurl: ""

google_analytics_id: "UA-1132651-2"

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/stevenmaguire
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon: github
    url:  https://github.com/stevenmaguire
    desc: Fork me on github
    share_url:
    share_title:
    share_link:
