# Site settings
title: Steven Maguire
email: "&#115;&#116;&#101;&#118;&#101;&#110;&#109;&#097;&#103;&#117;&#105;&#114;&#101;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"
description: >
  Builder of Teams, Software Architect, and Product Designer living in Chicago, IL
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

google_analytics_id: "UA-1132651-2"

twitter_username: stevenmaguire
github_username: stevenmaguire

# Build settings
markdown: kramdown

# projects
projects:
  - name: "Axis of Stevil"
    image: /img/portfolio/1.jpg
    url: http://www.axisofstevil.com
  - name: "logs.email"
    image: /img/portfolio/2.jpg
    url: https://logs.email
  - name: "Megawatt Labs"
    image: /img/portfolio/3.jpg
    url: http://www.gomegawatt.com
  - name: "Whiskey Muzzle"
    image: /img/portfolio/4.jpg
    url: http://www.whiskeymuzzle.com
  - name: "All Stars Project"
    image: /img/portfolio/5.jpg
    url: http://allstars.org/content/all-stars-project-chicago
  - name: "Graphic Art"
    image: /img/portfolio/6.jpg
    url: /art

# logos
logos:
  - image: axis-of-stevil.jpg
    client: "Axis of Stevil"
  - image: force-atv.jpg
    client: "Force ATV"
  - image: gnc-academy.jpg
    client: "Greenville, NC Citizens Academy"
  - image: gnc-aquafit.jpg
    client: "Greenville, NC Aquatics and Fitness Center"
  - image: gnc-bunkerz.jpg
    client: "Greenville, NC Bunkerz the Clown"
  - image: gnc-chili.jpg
    client: "Greenville, NC Chili Cook-off"
  - image: gnc-gtv9.jpg
    client: "Greenville, NC GTV 9"
  - image: gnc-ifest.jpg
    client: "Greenville, NC International Festival"
  - image: gnc-kgb.jpg
    client: "Greenville, NC Keep Greenville Beautiful"
  - image: gnc-pal.jpg
    client: "Greenville, NC Police Athletic League"
  - image: gnc-recycles.jpg
    client: "Greenville, NC Recycles"
  - image: gnc-stormwater.jpg
    client: "Greenville, NC Stormwater Management"
  - image: gnc-take-heed.jpg
    client: "Greenville, NC Take Heed Community Guide"
  - image: gnc-wifi.jpg
    client: "Greenville, NC Free Pulbic Wifi"
  - image: nc-go-green.jpg
    client: "North Carolina Go Green"
  - image: outback-outfitters.jpg
    client: "Outback Outfitters"
  - image: peoples-free-internet.jpg
    client: "People's Free Internet"
  - image: philmont.jpg
    client: "Philmont"
  - image: random-dewers.jpg
    client: "Random Dewers"
  - image: riverrock.jpg
    client: "Greenville RiverRock Festival"
  - image: search-dot-travel.jpg
    client: "Search.Travel"
  - image: signal-consulting.jpg
    client: "Signal Consulting"
  - image: site-swell.jpg
    client: "SiteSwell"
  - image: sparkling-clean.jpg
    client: "Sparkling Clean"
  - image: steven-maguire.jpg
    client: "Steven Maguire"
  - image: watershed.jpg
    client: "Watershed Holdings"
  - image: web-hosting-llc.jpg
    client: "Web Hosting, LLC."

# open source projects
opensource:
  - name: oauth2-github
    description: "GitHub Provider for the OAuth 2.0 Client"
    url: https://github.com/thephpleague/oauth2-github
    language: PHP
    role: Maintainer
  - name: oauth2-instagram
    description: "Instagram Provider for the OAuth 2.0 Client"
    url: https://github.com/thephpleague/oauth2-instagram
    language: PHP
    role: Maintainer
  - name: oauth2-linkedin
    description: "Linkedin Provider for the OAuth 2.0 Client"
    url: https://github.com/thephpleague/oauth2-linkedin
    language: PHP
    role: Maintainer
  - name: oauth2-foursquare
    description: "Foursquare Provider for the OAuth 2.0 Client"
    url: https://github.com/stevenmaguire/oauth2-foursquare
    language: PHP
    role: Maintainer
  - name: oauth2-paypal
    description: "PayPal Provider for the OAuth 2.0 Client"
    url: https://github.com/stevenmaguire/oauth2-paypal
    language: PHP
    role: Maintainer
  - name: oauth2-salesforce
    description: "Salesforce Provider for the OAuth 2.0 Client"
    url: https://github.com/stevenmaguire/oauth2-salesforce
    language: PHP
    role: Maintainer
  - name: oauth2-keycloak
    description: "Keycloak Provider for the OAuth 2.0 Client"
    url: https://github.com/stevenmaguire/oauth2-keycloak
    language: PHP
    role: Maintainer
  - name: oauth2-box
    description: "Box Provider for the OAuth 2.0 Client"
    url: https://github.com/stevenmaguire/oauth2-box
    language: PHP
    role: Maintainer
  - name: oauth2-bitbucket
    description: "Bitbucket Provider for the OAuth 2.0 Client"
    url: https://github.com/stevenmaguire/oauth2-bitbucket
    language: PHP
    role: Maintainer
  - name: oauth2-uber
    description: "Uber Provider for the OAuth 2.0 Client"
    url: https://github.com/stevenmaguire/oauth2-uber
    language: PHP
    role: Maintainer
  - name: oauth2-eventbrite
    description: "Eventbrite Provider for the OAuth 2.0 Client"
    url: https://github.com/stevenmaguire/oauth2-eventbrite
    language: PHP
    role: Maintainer
  - name: oauth2-microsoft
    description: "Microsoft Provider for the OAuth 2.0 Client"
    url: https://github.com/stevenmaguire/oauth2-microsoft
    language: PHP
    role: Maintainer
  - name: oauth2-elance
    description: "Elance Provider for the OAuth 2.0 Client"
    url: https://github.com/stevenmaguire/oauth2-elance
    language: PHP
    role: Maintainer
  - name: oauth1-trello
    description: "Trello Provider for the OAuth 1.0 Client"
    url: https://github.com/thephpleague/oauth1-trello
    language: PHP
    role: Maintainer
  - name: oauth1-bitbucket
    description: "Bitbucket Provider for the OAuth 1.0 Client"
    url: https://github.com/thephpleague/oauth1-bitbucket
    language: PHP
    role: Maintainer
  - name: yelp-php
    description: "A PHP client for consuming Yelp API"
    url: https://github.com/stevenmaguire/yelp-php
    language: PHP
    role: Maintainer
  - name: oauth-tool-php
    description: "A PHP application for retrieving OAuth 1 and 2 access credentials"
    url: https://github.com/stevenmaguire/oauth-tool-php
    language: PHP
    role: Maintainer
  - name: middleware-csp-php
    description: "Provides support for enforcing Content Security Policy with headers in PSR 7 responses"
    url: https://github.com/stevenmaguire/middleware-csp-php
    language: PHP
    role: Maintainer
  - name: trello-php
    description: "A PHP client for consuming Trello API"
    url: https://github.com/stevenmaguire/trello-php
    language: PHP
    role: Maintainer
  - name: encoding-php
    description: "A PHP client for consuming Encoding.com API"
    url: https://github.com/stevenmaguire/encoding-php
    language: PHP
    role: Maintainer
  - name: uber-php
    description: "A PHP client for consuming Uber API"
    url: https://github.com/stevenmaguire/uber-php
    language: PHP
    role: Maintainer
  - name: proxy-php
    description: "A PHP application for proxying requests to remote servers from a static IP"
    url: https://github.com/stevenmaguire/proxy-php
    language: PHP
    role: Maintainer
  - name: laravel-cache
    description: "Seamlessly adding caching to Laravel service objects"
    url: https://github.com/stevenmaguire/laravel-cache
    language: PHP
    role: Maintainer
  - name: laravel-middleware-csp
    description: "Provides support for enforcing Content Security Policy with headers in Laravel responses"
    url: https://github.com/stevenmaguire/laravel-middleware-csp
    language: PHP
    role: Maintainer
  - name: laravel-uuid-model
    description: "Create non-incrementing Laravel models whose primary key is a UUID"
    url: https://github.com/stevenmaguire/laravel-uuid-model
    language: PHP
    role: Maintainer
  - name: elvish-ipsum
    description: "Add Elvish words, sentences, and paragraphs to your Laravel project"
    url: https://github.com/stevenmaguire/elvish-ipsum
    language: PHP
    role: Maintainer
  - name: zurb-foundation-laravel
    description: "Build HTML form elements for Foundation inside Laravel 4"
    url: https://github.com/stevenmaguire/zurb-foundation-laravel
    language: PHP
    role: Maintainer
  - name: jobs-common
    description: "Making it simple to integrate your application with job API providers"
    url: https://github.com/JobBrander/jobs-common
    language: PHP
    role: Maintainer
  - name: jobs-authenticjobs
    description: "Making it simple to integrate your application with Authentic Jobs API"
    url: https://github.com/JobBrander/jobs-authenticjobs
    language: PHP
    role: Maintainer
  - name: jobs-indeed
    description: "Making it simple to integrate your application with Indeed Jobs API"
    url: https://github.com/JobBrander/jobs-indeed
    language: PHP
    role: Maintainer
  - name: jobs-github
    description: "Making it simple to integrate your application with Github Jobs API"
    url: https://github.com/JobBrander/jobs-github
    language: PHP
    role: Maintainer
  - name: jobs-elance
    description: "Making it simple to integrate your application with Elance Jobs API"
    url: https://github.com/JobBrander/jobs-elance
    language: PHP
    role: Maintainer
  - name: oauth2-client
    description: "Easy integration with OAuth 2.0 service providers"
    url: https://github.com/thephpleague/oauth2-client
    language: PHP
    role: Contributor
  - name: oauth1-client
    description: "An OAuth RFC 5849 standards-compliant library for authenticating against OAuth 1 servers"
    url: https://github.com/thephpleague/oauth1-client
    language: PHP
    role: Contributor
  - name: oauth2-dropbox
    description: "Dropbox Provider for the OAuth 2.0 Client"
    url: https://github.com/pixelfear/oauth2-dropbox
    language: PHP
    role: Contributor

#theatre projects
theatre:
  - title: "Overtones by Alice Gerstenberg & Lorin Howard"
    season: "Spring - 2008"
    dates: "May 22 - 31, 2008"
    role: "Technical Director"
    department: "Scenic Construction"
  - title: "Enemies by Joseph Horst"
    season: "Spring - 2008"
    dates: "February 16 - 19, 2008"
    role: "Production Consultant"
    department: "Production Administration"
  - title: "The Rivals by Richard Brinsley Sheridan*"
    season: "Spring - 2004"
    dates: "April 15 - 20, 2004"
    role: "Master Carpenter"
    department: "Scenic Construction"
  - title: "The Grapes of Wrath by Frank Galati after John Steinbeck*"
    season: "Spring - 2004"
    dates: "February 19 - 24, 2004"
    role: "Master Carpenter"
    department: "Scenic Construction"
  - title: "The Grapes of Wrath by Frank Galati after John Steinbeck*"
    season: "Spring - 2004"
    dates: "February 19 - 24, 2004"
    role: "Stage Carpenter"
    department: "Scenic Construction"
  - title: "Dance 2004*"
    season: "Spring - 2004"
    dates: "January 29 - February 3, 2004"
    role: "Technical Assistant"
    department: "Scenic Construction"
  - title: "Yerma by Garcia Lorca*"
    season: "Fall - 2003"
    dates: "November 20-25, 2003"
    role: "Master Carpenter"
    department: "Scenic Construction"
  - title: "A Chorus Line by James Kirkwood, Nicholas Dante, Marvin Hamlisch and Edward Kleban*"
    season: "Fall - 2003"
    dates: "October 2 - 7, 2003"
    role: "Master Carpenter"
    department: "Scenic Construction"
  - title: "Merton of the Movies by George S. Kaufman and Marc Connelly*"
    season: "Spring - 2003"
    dates: "April 10 - 15, 2003"
    role: "Technical Assistant"
    department: "Scenic Construction"
  - title: "Bacchai by Euripides*"
    season: "Spring - 2003"
    dates: "February 20 - 25, 2003"
    role: "Scenic Artist"
    department: "Paints and Properties"
  - title: "Bacchai by Euripides*"
    season: "Spring - 2003"
    dates: "February 20 - 25, 2003"
    role: "Technical Assistant"
    department: "Scenic Construction"
  - title: "Dance 2003*"
    season: "Spring - 2003"
    dates: "January 30 - February 4, 2003"
    role: "Paint and Properties Crew"
    department: "Paints and Properties"
  - title: "Dance 2003*"
    season: "Spring - 2003"
    dates: "January 30 - February 4, 2003"
    role: "Technical Assistant"
    department: "Scenic Construction"
  - title: "Picnic by William Inge*"
    season: "Fall - 2002"
    dates: "November 21 - 26, 2002"
    role: "Scenery Construction Crew"
    department: "Scenic Construction"
  - title: "My Fair Lady by Alan Jay Lerner and Frederick Loewe*"
    season: "Fall - 2002"
    dates: "October 3-8, 2002"
    role: "Scenery Construction Crew"
    department: "Scenic Construction"
