# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Steven Maguire"
description: > # this means to ignore newlines until "email:"
   Builder of Teams, Software Architect and Product Designer living in Chicago, IL

email: stevenmaguire@gmail.com
#blog logo
logo: "http://stevenmaguire-com.s3.amazonaws.com/assets/logo.png"
# blog cover
cover: "http://stevenmaguire-com.s3.amazonaws.com/assets/1487799_10101504743938103_1110083647_o.jpg"

name: 'Steven Maguire'
author: 'Steven Maguire'
author_image: "http://stevenmaguire-com.s3.amazonaws.com/assets/steven.png"

paginate: 5

url: "http://stevenmaguire.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/stevenmaguire
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:  facebook
#    url: https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/stevenmaguire
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:  google-plus
#    url: https://google.com/???
#    desc:  Add me on google+
#    share_url:
#    share_title:
#    share_link:
